### ISSUE TITLE
格力空调的二进制文件通过网络请求无法下载

### ISSUE THREAD

**Issue by Caffreyfans** [irext/irext-core#4]
经长期使用发现，格力空调的二进制文件通过post请求无法获取到，返回错误号为 204。其余文件暂时为发现错误。下载不了的文件id有 12984、13021。请你确认一下是否有误。

**Comment by strawmanbobi** [comment]
GOT, THANKS
On Sep 20, 2018 8:00 AM, Caffreyfans <notifications@github.com> wrote:经长期使用发现，格力空调的二进制文件通过post请求无法获取到，返回错误号为 204。其余文件暂时为发现错误。下载不了的文件id有 12984、13021。请你确认一下是否有误。

**Comment by strawmanbobi** [comment]
由于在索引服务中没有过滤掉那些验证不通过的index导致的，已经修正。
谢谢指出！
